# Generated by Django 3.2 on 2022-03-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_detail',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
